# remote_theme: pages-themes/leap-day@v0.2.0
# remote_theme: just-the-docs/just-the-docs
remote_theme: sighingnow/jekyll-gitbook
markdown: kramdown
title: "Lynn's C++ Notes"

# Code highlight style
syntax_highlighter_style: custom

# To be displayed on the sidebar
collections_dir: notes
collections:
  language_features:
    output: true
    permalink: /:collection/:name/
  cminusminus:
    output: true
    permalink: /:collection/:name/

# Sidebar category ordering
ordered_collections:
  - language_features
  - cminusminus

# Jekyll-toc generates contents per file
toc:
  enabled: true

# Plugins
plugins:
- jekyll-remote-theme
